### ISSUE TITLE
Link to sample collection principles on the About page

### ISSUE THREAD

**Issue by lauraclarke** [EMBL-EBI-GCA/gca_1000genomes_website#2]
@istreeter @susanfairley 

I haven't removed it but while editing the about page

https://github.com/EMBL-EBI-GCA/gca_1000genomes_website/blob/master/_searchable/about.md

I feel that the headline link to the samplecollections page seems like a non-sequitur

Is there a rationale behind having that link there rather than just futher down the page?

**Comment by susanfairley** [comment]
This has been removed, leaving the link in the body of the text further down the page.
